name: Build Tesla Overlay

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make

          # Install libtesla
          git clone https://github.com/WerWolv/libtesla.git
          cd libtesla
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Build overlay
        run: make -j$(nproc)

      - name: Upload .ovl artifact
        uses: actions/upload-artifact@v4
        with:
          name: tesla_lux_overlay
          path: build/*.ovl
